import type { Metadata } from "next";
import Link from "next/link";
import { ProductFooter, ProductNav } from "../../site-nav";

export const metadata: Metadata = { title: "Laboratory dispute workflow demonstration — TEC Registry", robots: { index: false, follow: true } };

const analytes = [["Lead", "31 µg/kg", "48 µg/kg", "1.55× spread"], ["Cadmium", "12 µg/kg", "14 µg/kg", "1.17× spread"], ["Arsenic", "< 10 µg/kg", "18 µg/kg", "Reporting-limit review"]];
export default function LabDefenseDemoPage() {
  return <main className="product-page lab-defense-demo-page"><ProductNav compact /><header className="product-hero lab-defense-demo-hero"><p className="section-kicker light">Fictional laboratory workflow</p><h1>Stop arguing over<br />two detached PDFs.</h1><p>See how TECRID can answer authenticity immediately, align two result sets, and package the unresolved scientific questions for qualified review.</p><div className="draft-standard-badge"><i /> Invented laboratories · invented values · no real TECRIDs</div></header>
    <div className="lab-defense-demo-shell"><section className="verification-demo-strip"><article><span>01 · Authenticity</span><strong>Both registry records resolve</strong><p>Issuer status, signatures, fingerprints, and version history are visible without calling either laboratory.</p></article><article><span>02 · Comparability</span><strong>Technical review required</strong><p>The lot aligns, but the methods and reporting limits do not. TECRID does not declare a winner.</p></article><article><span>03 · Handoff</span><strong>One frozen evidence manifest</strong><p>Both record versions and the missing-context checklist travel together.</p></article></section>
    <section className="demo-dispute-card"><div className="panel-heading"><div><p className="section-kicker">Fictional lot AB-2408</p><h2>Laboratory A ↔ Laboratory B</h2></div><span className="record-status record-requires_scientific_review">requires scientific review</span></div><div className="dispute-context-table"><div><strong>Sample name</strong><span>Organic cacao powder</span><span>Organic cacao powder</span><i className="context-aligned">aligned</i></div><div><strong>Lot number</strong><span>AB-2408</span><span>AB-2408</span><i className="context-aligned">aligned</i></div><div><strong>Method</strong><span>AOAC 2015.01 · ICP-MS</span><span>In-house M-44 · ICP-MS</span><i className="context-different">different</i></div>{analytes.map((row) => <div key={row[0]}><strong>{row[0]}</strong><span>{row[1]}</span><span>{row[2]}</span><i>{row[3]}</i></div>)}</div></section>
    <section className="dispute-missing"><div><p className="section-kicker light">The useful output</p><h2>Replace “which PDF is right?” with an answerable review.</h2></div><ul><li>Confirm the sampling plan and sample identity</li><li>Reconcile wet- or dry-weight basis</li><li>Review measurement uncertainty</li><li>Compare digestion, preparation, and QC records</li><li>Document the scientific conclusion outside TECRID</li></ul></section>
    <section className="disclosure-demo-measurement"><div><p className="section-kicker">The 10× test</p><h2>Measure calls and reconstruction work eliminated.</h2></div><div className="disclosure-math"><article><span>Detached-PDF model</span><strong>2 labs × many calls</strong><p>Locate reports, authenticate copies, identify versions, re-key values, and ask for missing context.</p></article><article><span>TECRID model</span><strong>2 IDs → 1 case</strong><p>Resolve, align, fingerprint, and hand off. Scientific interpretation remains human work.</p></article></div><p className="measurement-boundary">This is workflow logic, not a claimed customer result. A pilot should time report-verification contacts, case assembly, re-entry, and technical-review preparation.</p></section>
    <section className="disclosure-demo-cta"><div><p className="section-kicker light">Run the authenticated workflow</p><h2>Create evidence cases from real public TECRIDs.</h2><p>Organizations can preserve both record versions and the comparison manifest without asking TECRID to exceed its evidentiary role.</p></div><Link className="button-mint" href="/dashboard/lab-defense">Open laboratory desk →</Link></section></div><ProductFooter /></main>;
}
