"use client";

import { useRef, useState } from "react";

type Result = { intakeId: string; status: string; rowCount: number; validRows: number; blockedRows: number; manifestFingerprint: string; items: Array<{ rowNumber: number; submittedIdentifier: string; validationStatus: string; errors: string[] }> };
export function CertificationSubmissionClient({ token, email, displayName, programName, receiverName }: { token: string; email: string; displayName: string; programName: string; receiverName: string }) {
  const fileRef = useRef<HTMLInputElement>(null);
  const [applicantOrganization, setApplicantOrganization] = useState("");
  const [applicantName, setApplicantName] = useState(displayName);
  const [applicantEmail, setApplicantEmail] = useState(email);
  const [submissionReference, setSubmissionReference] = useState("");
  const [csv, setCsv] = useState(""); const [filename, setFilename] = useState("");
  const [message, setMessage] = useState("CSV requires one column named tecrid. Up to 100 identifiers and 1 MB.");
  const [result, setResult] = useState<Result | null>(null); const [busy, setBusy] = useState(false);
  async function choose(file?: File) { if (!file) return; setFilename(file.name); setCsv(await file.text()); setResult(null); setMessage(`${file.name} loaded. Submit when ready.`); }
  async function submit() { setBusy(true); setResult(null); setMessage("Resolving every TECRID and freezing the reviewed record versions…"); try { const response = await fetch(`/api/certification/submit/${encodeURIComponent(token)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ applicantOrganization, applicantName, applicantEmail, submissionReference, csv }) }); const body = await response.json() as { result?: Result; error?: string }; if (!response.ok || !body.result) throw new Error(body.error || "Submission failed."); setResult(body.result); setMessage("Submission received. Review any blocked rows below."); } catch (error) { setMessage(error instanceof Error ? error.message : "Submission failed."); } finally { setBusy(false); } }
  return <div className="certification-submit-shell"><section className="certification-submit-boundary"><strong>Authority gate</strong><p>Only current production TECRIDs from verified laboratories with valid signatures, fingerprints, and version history can pass. Resolver samples are always blocked. Passing the gate does not award certification.</p></section><section className="certification-submit-grid"><div className="certification-applicant-form"><p className="section-kicker">Applicant</p><h2>Identify this evidence package.</h2><label>Organization<input value={applicantOrganization} onChange={(event) => setApplicantOrganization(event.target.value)} /></label><div className="form-pair"><label>Contact name<input value={applicantName} onChange={(event) => setApplicantName(event.target.value)} /></label><label>Contact email<input type="email" value={applicantEmail} onChange={(event) => setApplicantEmail(event.target.value)} /></label></div><label>Submission reference <span>optional</span><input value={submissionReference} onChange={(event) => setSubmissionReference(event.target.value)} placeholder="Application or product reference" /></label></div><div className="certification-csv-form"><p className="section-kicker light">Evidence list</p><h2>Upload TECRID CSV</h2><input ref={fileRef} className="sr-only" type="file" accept=".csv,text/csv" onChange={(event) => void choose(event.target.files?.[0])} /><button type="button" className="certification-file-button" onClick={() => fileRef.current?.click()}><span>{filename || "Choose a CSV file"}</span><small>Required header: tecrid</small></button><a href="/templates/certification-tecrid-intake.csv" download>Download CSV template ↓</a><button type="button" className="button-mint" disabled={busy || !csv} onClick={() => void submit()}>{busy ? "Validating…" : `Submit to ${receiverName} →`}</button><p aria-live="polite">{message}</p></div></section>{result ? <section className={`certification-submit-result result-${result.status}`}><div><p className="section-kicker">Submission result</p><h2>{result.status.replaceAll("_", " ")}</h2><p>{result.validRows} of {result.rowCount} TECRIDs passed the evidence gate. {result.blockedRows ? `${result.blockedRows} require correction before review.` : `The ${programName} team can now review the frozen package.`}</p><code>{result.manifestFingerprint}</code></div><div className="certification-row-results">{result.items.map((item) => <div key={item.rowNumber}><span>Row {item.rowNumber}</span><strong>{item.submittedIdentifier}</strong><i>{item.validationStatus}</i>{item.errors.length ? <small>{item.errors.join("; ")}</small> : null}</div>)}</div></section> : null}</div>;
}
