import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { requireChatGPTUser } from "../../../chatgpt-auth";
import { getCertificationIntakeForUser } from "../../../../lib/certification";
import { ProductFooter, ProductNav } from "../../../site-nav";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Certification evidence package — TEC Registry" };
type RouteContext = { params: Promise<{ intakeId: string }> };
export default async function CertificationIntakePage({ params }: RouteContext) {
  const { intakeId } = await params; const user = await requireChatGPTUser(`/dashboard/certification/${intakeId}`); const record = await getCertificationIntakeForUser(user, intakeId); if (!record) notFound();
  return <main className="product-page certification-intake-detail"><ProductNav compact /><header className="record-page-hero certification-detail-hero"><div><p className="section-kicker light">Certification evidence package</p><h1>{record.intake.applicantOrganization}</h1><p>{record.program.name} · {record.intake.submissionReference || "No applicant reference"}</p></div><span className="workspace-code">Validation <strong>{record.intake.status.replaceAll("_", " ")}</strong></span></header><div className="certification-detail-shell"><section className="certification-submit-boundary"><strong>Evidence intake—not certification</strong><p>This package proves which public TECRID versions passed the registry gate at submission time. The receiving organization must still perform its own scope, criteria, sampling, and certification review.</p></section><section className="certification-detail-summary"><article><span>Submitted</span><strong>{new Date(record.intake.createdAt).toLocaleString()}</strong><small>{record.intake.sourceType.toUpperCase()} intake</small></article><article><span>Applicant contact</span><strong>{record.intake.applicantName}</strong><small>{record.intake.applicantEmail}</small></article><article><span>Rows</span><strong>{record.intake.validRows} valid / {record.intake.blockedRows} blocked</strong><small>{record.intake.rowCount} total</small></article></section><section className="dashboard-panel certification-intake-log"><div className="panel-heading"><div><p className="section-kicker">Row validation</p><h2>Exact records reviewed</h2></div><a className="button-dark" href={`/api/certification/intakes/${record.intake.id}/manifest`}>Download manifest ↓</a></div><div className="certification-detail-fingerprint"><span>Package fingerprint</span><code>{record.intake.manifestFingerprint}</code></div><div className="certification-intake-list detail-list">{record.items.map((item) => { const errors = item.errors ? JSON.parse(item.errors) as string[] : []; return <article key={item.id}><span className={`record-status record-${item.validationStatus}`}>{item.validationStatus}</span><div><strong>{item.normalizedIdentifier || item.submittedIdentifier}</strong><small>{errors.length ? errors.join("; ") : `Version ${item.recordVersion} · signature verified`}</small></div><div>{item.credentialIdentifier ? <a href={`/records/${encodeURIComponent(item.credentialIdentifier)}`}>Resolve ↗</a> : null}<small>{item.snapshotFingerprint ? `${item.snapshotFingerprint.slice(0, 12)}…` : "No snapshot"}</small></div></article>; })}</div></section></div><ProductFooter /></main>;
}
